"""Set Click events user agent col name to browsers

Revision ID: 0c21f16a4018
Revises: 3f5c2ddaf709
Create Date: 2026-04-25 10:54:08.263545

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c21f16a4018"
down_revision: Union[str, Sequence[str], None] = "3f5c2ddaf709"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kombu_message_timestamp"), table_name="kombu_message")
    op.drop_index(op.f("ix_kombu_message_timestamp_id"), table_name="kombu_message")
    op.drop_index(op.f("ix_kombu_message_visible"), table_name="kombu_message")
    op.drop_table("kombu_message")
    op.drop_index(op.f("ix_celery_taskmeta_date_done"), table_name="celery_taskmeta")
    op.drop_table("celery_taskmeta")
    op.drop_table("kombu_queue")
    op.drop_index(
        op.f("ix_celery_tasksetmeta_date_done"), table_name="celery_tasksetmeta"
    )
    op.drop_table("celery_tasksetmeta")
    op.add_column(
        "clickevents",
        sa.Column("browser", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("clickevents", "user_agent")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clickevents",
        sa.Column("user_agent", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("clickevents", "browser")
    op.create_table(
        "celery_tasksetmeta",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "taskset_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True
        ),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column(
            "date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("celery_tasksetmeta_pkey")),
        sa.UniqueConstraint(
            "taskset_id",
            name=op.f("celery_tasksetmeta_taskset_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_celery_tasksetmeta_date_done"),
        "celery_tasksetmeta",
        ["date_done"],
        unique=False,
    )
    op.create_table(
        "kombu_queue",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("kombu_queue_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("kombu_queue_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "celery_taskmeta",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column(
            "date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("traceback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("args", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("kwargs", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("worker", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("retries", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("queue", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("celery_taskmeta_pkey")),
        sa.UniqueConstraint(
            "task_id",
            name=op.f("celery_taskmeta_task_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_celery_taskmeta_date_done"),
        "celery_taskmeta",
        ["date_done"],
        unique=False,
    )
    op.create_table(
        "kombu_message",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("visible", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("payload", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("queue_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["queue_id"], ["kombu_queue.id"], name=op.f("FK_kombu_message_queue")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kombu_message_pkey")),
    )
    op.create_index(
        op.f("ix_kombu_message_visible"), "kombu_message", ["visible"], unique=False
    )
    op.create_index(
        op.f("ix_kombu_message_timestamp_id"),
        "kombu_message",
        ["timestamp", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kombu_message_timestamp"), "kombu_message", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###
