"""Updated Links table schema to add a name column and add indexing to status

Revision ID: 42504796ba6e
Revises: 33369c5c2243
Create Date: 2026-04-21 13:30:52.460403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42504796ba6e'
down_revision: Union[str, Sequence[str], None] = '33369c5c2243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clickevents', 'links', ['link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clickevents', type_='foreignkey')
    # ### end Alembic commands ###
