"""Set Click events ip address to index true

Revision ID: 861de75c8c9b
Revises: 0c21f16a4018
Create Date: 2026-04-26 18:00:00.282466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861de75c8c9b'
down_revision: Union[str, Sequence[str], None] = '0c21f16a4018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clickevents_ip_address'), 'clickevents', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clickevents_ip_address'), table_name='clickevents')
    # ### end Alembic commands ###
