/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteRouteImport } from './routes/me/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as MeViewIndexRouteImport } from './routes/me/view/index'
import { Route as MeAddIndexRouteImport } from './routes/me/add/index'
import { Route as MeViewLinkidRouteImport } from './routes/me/view/$linkid'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRouteRoute = MeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeViewIndexRoute = MeViewIndexRouteImport.update({
  id: '/view/',
  path: '/view/',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeAddIndexRoute = MeAddIndexRouteImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeViewLinkidRoute = MeViewLinkidRouteImport.update({
  id: '/view/$linkid',
  path: '/view/$linkid',
  getParentRoute: () => MeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/me/': typeof MeIndexRoute
  '/me/view/$linkid': typeof MeViewLinkidRoute
  '/me/add/': typeof MeAddIndexRoute
  '/me/view/': typeof MeViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/me': typeof MeIndexRoute
  '/me/view/$linkid': typeof MeViewLinkidRoute
  '/me/add': typeof MeAddIndexRoute
  '/me/view': typeof MeViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/me/': typeof MeIndexRoute
  '/me/view/$linkid': typeof MeViewLinkidRoute
  '/me/add/': typeof MeAddIndexRoute
  '/me/view/': typeof MeViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/login'
    | '/register'
    | '/me/'
    | '/me/view/$linkid'
    | '/me/add/'
    | '/me/view/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/me'
    | '/me/view/$linkid'
    | '/me/add'
    | '/me/view'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/login'
    | '/register'
    | '/me/'
    | '/me/view/$linkid'
    | '/me/add/'
    | '/me/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRouteRoute: typeof MeRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/view/': {
      id: '/me/view/'
      path: '/view'
      fullPath: '/me/view/'
      preLoaderRoute: typeof MeViewIndexRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/add/': {
      id: '/me/add/'
      path: '/add'
      fullPath: '/me/add/'
      preLoaderRoute: typeof MeAddIndexRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/view/$linkid': {
      id: '/me/view/$linkid'
      path: '/view/$linkid'
      fullPath: '/me/view/$linkid'
      preLoaderRoute: typeof MeViewLinkidRouteImport
      parentRoute: typeof MeRouteRoute
    }
  }
}

interface MeRouteRouteChildren {
  MeIndexRoute: typeof MeIndexRoute
  MeViewLinkidRoute: typeof MeViewLinkidRoute
  MeAddIndexRoute: typeof MeAddIndexRoute
  MeViewIndexRoute: typeof MeViewIndexRoute
}

const MeRouteRouteChildren: MeRouteRouteChildren = {
  MeIndexRoute: MeIndexRoute,
  MeViewLinkidRoute: MeViewLinkidRoute,
  MeAddIndexRoute: MeAddIndexRoute,
  MeViewIndexRoute: MeViewIndexRoute,
}

const MeRouteRouteWithChildren =
  MeRouteRoute._addFileChildren(MeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRouteRoute: MeRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
